name: Backend API Tests

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  detect-changes:
    name: Detect Changed Backend Files
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.detect.outputs.should_skip }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # Ensure we have the actual PR commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Detect Relevant Changes
        id: detect
        run: |
          # Fetch base ref to compare
          git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}

          # List changed files (added or modified)
          CHANGED_FILES="$(git diff --name-only --diff-filter=AM HEAD origin/${{ github.base_ref }})"
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # If changes match the patterns, we do NOT skip
          if echo "$CHANGED_FILES" | grep -qE '^app/backend/app/|^scripts/test_api.sh$'; then
            echo "should_skip=false" >> "$GITHUB_OUTPUT"
          else
            echo "should_skip=true" >> "$GITHUB_OUTPUT"
          fi

  tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.should_skip == 'false' }}
    env:
      secret_key: ${{ secrets.SECRET_KEY }}
      algorithm: ${{ secrets.ALGORITHM }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Ensure we have the actual PR commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install uv
          uv sync --group test --no-dev

      - name: Run API Tests
        run: |
          uv run bash scripts/test_api.sh
